/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminAuthRouteImport } from './routes/admin-auth'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as BlogAdminRouteImport } from './routes/blog-admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactDothtmlRouteImport } from './routes/contact[.]html'
import { Route as CurrentAuctionsDothtmlRouteImport } from './routes/current-auctions[.]html'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowMuchDoEstateSaleCompaniesChargeRouteImport } from './routes/how-much-do-estate-sale-companies-charge'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as WhyWorkWithUsRouteImport } from './routes/why-work-with-us'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesCategorySlugRouteImport } from './routes/services/$categorySlug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable/oauth/consent'
import { Route as AreasSlugIndexRouteImport } from './routes/areas/$slug/index'
import { Route as AreasSlugServiceSlugRouteImport } from './routes/areas/$slug/$serviceSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin-auth',
  path: '/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminRoute = BlogAdminRouteImport.update({
  id: '/blog-admin',
  path: '/blog-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactDothtmlRoute = ContactDothtmlRouteImport.update({
  id: '/contact.html',
  path: '/contact.html',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAuctionsDothtmlRoute = CurrentAuctionsDothtmlRouteImport.update({
  id: '/current-auctions.html',
  path: '/current-auctions.html',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowMuchDoEstateSaleCompaniesChargeRoute =
  HowMuchDoEstateSaleCompaniesChargeRouteImport.update({
    id: '/how-much-do-estate-sale-companies-charge',
    path: '/how-much-do-estate-sale-companies-charge',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyWorkWithUsRoute = WhyWorkWithUsRouteImport.update({
  id: '/why-work-with-us',
  path: '/why-work-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategorySlugRoute = ServicesCategorySlugRouteImport.update({
  id: '/services/$categorySlug',
  path: '/services/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugIndexRoute = AreasSlugIndexRouteImport.update({
  id: '/areas/$slug/',
  path: '/areas/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugServiceSlugRoute = AreasSlugServiceSlugRouteImport.update({
  id: '/areas/$slug/$serviceSlug',
  path: '/areas/$slug/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-auth': typeof AdminAuthRoute
  '/auctions': typeof AuctionsRoute
  '/blog-admin': typeof BlogAdminRoute
  '/contact': typeof ContactRoute
  '/contact.html': typeof ContactDothtmlRoute
  '/current-auctions.html': typeof CurrentAuctionsDothtmlRoute
  '/faq': typeof FaqRoute
  '/how-much-do-estate-sale-companies-charge': typeof HowMuchDoEstateSaleCompaniesChargeRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-us': typeof WhyUsRoute
  '/why-work-with-us': typeof WhyWorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$categorySlug': typeof ServicesCategorySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/areas/$slug/$serviceSlug': typeof AreasSlugServiceSlugRoute
  '/areas/$slug/': typeof AreasSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-auth': typeof AdminAuthRoute
  '/auctions': typeof AuctionsRoute
  '/blog-admin': typeof BlogAdminRoute
  '/contact': typeof ContactRoute
  '/contact.html': typeof ContactDothtmlRoute
  '/current-auctions.html': typeof CurrentAuctionsDothtmlRoute
  '/faq': typeof FaqRoute
  '/how-much-do-estate-sale-companies-charge': typeof HowMuchDoEstateSaleCompaniesChargeRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-us': typeof WhyUsRoute
  '/why-work-with-us': typeof WhyWorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$categorySlug': typeof ServicesCategorySlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/areas/$slug/$serviceSlug': typeof AreasSlugServiceSlugRoute
  '/areas/$slug': typeof AreasSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-auth': typeof AdminAuthRoute
  '/auctions': typeof AuctionsRoute
  '/blog-admin': typeof BlogAdminRoute
  '/contact': typeof ContactRoute
  '/contact.html': typeof ContactDothtmlRoute
  '/current-auctions.html': typeof CurrentAuctionsDothtmlRoute
  '/faq': typeof FaqRoute
  '/how-much-do-estate-sale-companies-charge': typeof HowMuchDoEstateSaleCompaniesChargeRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-us': typeof WhyUsRoute
  '/why-work-with-us': typeof WhyWorkWithUsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$categorySlug': typeof ServicesCategorySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/areas/$slug/$serviceSlug': typeof AreasSlugServiceSlugRoute
  '/areas/$slug/': typeof AreasSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-auth'
    | '/auctions'
    | '/blog-admin'
    | '/contact'
    | '/contact.html'
    | '/current-auctions.html'
    | '/faq'
    | '/how-much-do-estate-sale-companies-charge'
    | '/privacy'
    | '/privacy-policy'
    | '/search'
    | '/testimonials'
    | '/why-us'
    | '/why-work-with-us'
    | '/blog/$slug'
    | '/services/$categorySlug'
    | '/blog/'
    | '/services/'
    | '/.lovable/oauth/consent'
    | '/areas/$slug/$serviceSlug'
    | '/areas/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-auth'
    | '/auctions'
    | '/blog-admin'
    | '/contact'
    | '/contact.html'
    | '/current-auctions.html'
    | '/faq'
    | '/how-much-do-estate-sale-companies-charge'
    | '/privacy'
    | '/privacy-policy'
    | '/search'
    | '/testimonials'
    | '/why-us'
    | '/why-work-with-us'
    | '/blog/$slug'
    | '/services/$categorySlug'
    | '/blog'
    | '/services'
    | '/.lovable/oauth/consent'
    | '/areas/$slug/$serviceSlug'
    | '/areas/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-auth'
    | '/auctions'
    | '/blog-admin'
    | '/contact'
    | '/contact.html'
    | '/current-auctions.html'
    | '/faq'
    | '/how-much-do-estate-sale-companies-charge'
    | '/privacy'
    | '/privacy-policy'
    | '/search'
    | '/testimonials'
    | '/why-us'
    | '/why-work-with-us'
    | '/blog/$slug'
    | '/services/$categorySlug'
    | '/blog/'
    | '/services/'
    | '/.lovable/oauth/consent'
    | '/areas/$slug/$serviceSlug'
    | '/areas/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AuctionsRoute: typeof AuctionsRoute
  BlogAdminRoute: typeof BlogAdminRoute
  ContactRoute: typeof ContactRoute
  ContactDothtmlRoute: typeof ContactDothtmlRoute
  CurrentAuctionsDothtmlRoute: typeof CurrentAuctionsDothtmlRoute
  FaqRoute: typeof FaqRoute
  HowMuchDoEstateSaleCompaniesChargeRoute: typeof HowMuchDoEstateSaleCompaniesChargeRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WhyUsRoute: typeof WhyUsRoute
  WhyWorkWithUsRoute: typeof WhyWorkWithUsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesCategorySlugRoute: typeof ServicesCategorySlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  AreasSlugServiceSlugRoute: typeof AreasSlugServiceSlugRoute
  AreasSlugIndexRoute: typeof AreasSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-admin': {
      id: '/blog-admin'
      path: '/blog-admin'
      fullPath: '/blog-admin'
      preLoaderRoute: typeof BlogAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact.html': {
      id: '/contact.html'
      path: '/contact.html'
      fullPath: '/contact.html'
      preLoaderRoute: typeof ContactDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-auctions.html': {
      id: '/current-auctions.html'
      path: '/current-auctions.html'
      fullPath: '/current-auctions.html'
      preLoaderRoute: typeof CurrentAuctionsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-much-do-estate-sale-companies-charge': {
      id: '/how-much-do-estate-sale-companies-charge'
      path: '/how-much-do-estate-sale-companies-charge'
      fullPath: '/how-much-do-estate-sale-companies-charge'
      preLoaderRoute: typeof HowMuchDoEstateSaleCompaniesChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-work-with-us': {
      id: '/why-work-with-us'
      path: '/why-work-with-us'
      fullPath: '/why-work-with-us'
      preLoaderRoute: typeof WhyWorkWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$categorySlug': {
      id: '/services/$categorySlug'
      path: '/services/$categorySlug'
      fullPath: '/services/$categorySlug'
      preLoaderRoute: typeof ServicesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug/': {
      id: '/areas/$slug/'
      path: '/areas/$slug'
      fullPath: '/areas/$slug/'
      preLoaderRoute: typeof AreasSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug/$serviceSlug': {
      id: '/areas/$slug/$serviceSlug'
      path: '/areas/$slug/$serviceSlug'
      fullPath: '/areas/$slug/$serviceSlug'
      preLoaderRoute: typeof AreasSlugServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminAuthRoute: AdminAuthRoute,
  AuctionsRoute: AuctionsRoute,
  BlogAdminRoute: BlogAdminRoute,
  ContactRoute: ContactRoute,
  ContactDothtmlRoute: ContactDothtmlRoute,
  CurrentAuctionsDothtmlRoute: CurrentAuctionsDothtmlRoute,
  FaqRoute: FaqRoute,
  HowMuchDoEstateSaleCompaniesChargeRoute:
    HowMuchDoEstateSaleCompaniesChargeRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  TestimonialsRoute: TestimonialsRoute,
  WhyUsRoute: WhyUsRoute,
  WhyWorkWithUsRoute: WhyWorkWithUsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesCategorySlugRoute: ServicesCategorySlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  AreasSlugServiceSlugRoute: AreasSlugServiceSlugRoute,
  AreasSlugIndexRoute: AreasSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
