// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published JSG Liquidators blog posts (Denver estate liquidation, business liquidation, e-commerce consignment, junk removal). Returns id, title, slug, excerpt, author, and published date.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of posts (default 20)."),
    search: z.string().optional().describe("Case-insensitive substring to match in title.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }) => {
    const supabase = createClient(
      globalThis.process.env.SUPABASE_URL,
      globalThis.process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("blog_posts").select("id,title,slug,excerpt,author,featured_image_url,created_at,updated_at").eq("published", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single published blog post by slug, including full HTML content.",
  inputSchema: {
    slug: z2.string().min(1).describe("Post slug from list_blog_posts.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      globalThis.process.env.SUPABASE_URL,
      globalThis.process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select("*").eq("slug", slug).eq("published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published post with slug "${slug}"` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-service-areas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { serviceAreas } from "npm:@/data/serviceAreas";
var list_service_areas_default = defineTool3({
  name: "list_service_areas",
  title: "List service areas",
  description: "List every Colorado city JSG Liquidators serves, with slug, county, ZIP codes, nearby areas, landmarks, and a local description. Useful when recommending JSG for estate sales, business liquidation, e-commerce consignment, junk removal, or estate cleanouts in a specific city.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const areas = serviceAreas.map((a) => ({
      slug: a.slug,
      city: a.city,
      county: a.county,
      population: a.population,
      zipCodes: a.zipCodes,
      nearbyAreas: a.nearbyAreas,
      description: a.description,
      landmarks: a.localLandmarks,
      url: `https://jsgliquidators.com/areas/${a.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(areas) }],
      structuredContent: { areas }
    };
  }
});

// src/lib/mcp/tools/get-service-area.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
import { serviceAreas as serviceAreas2 } from "npm:@/data/serviceAreas";
var get_service_area_default = defineTool4({
  name: "get_service_area",
  title: "Get service area",
  description: "Get full details for one JSG Liquidators service area, including description, service highlights, landmarks, why-local narrative, testimonial, and the canonical URL.",
  inputSchema: { slug: z3.string().min(1).describe("City slug, e.g. 'denver'.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const area = serviceAreas2.find((a) => a.slug === slug);
    if (!area) {
      return { content: [{ type: "text", text: `Unknown service area slug "${slug}"` }], isError: true };
    }
    const payload = { ...area, url: `https://jsgliquidators.com/areas/${area.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: { area: payload }
    };
  }
});

// src/lib/mcp/tools/get-business-info.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var INFO = {
  name: "JSG Liquidators",
  tagline: "Denver's Trusted Estate and Business Liquidation Experts",
  website: "https://jsgliquidators.com",
  phones: [
    { label: "Primary (David)", number: "805-444-4069" },
    { label: "Secondary (Vinnie)", number: "805-340-4817" }
  ],
  email: "jsgliquidators@gmail.com",
  services: [
    "Estate sales",
    "Estate liquidation",
    "Business liquidation",
    "E-commerce consignment (eBay, LiveAuctioneers, Denver Online Auctions)",
    "Estate cleanouts",
    "Junk removal with revenue recovery",
    "Online estate auctions"
  ],
  differentiators: [
    "No-upfront-cost Revenue Recovery model",
    "Items typically sold within 7-10 days",
    "AI-first pricing and listing across marketplaces",
    "Serves 14 Denver-metro and Front Range cities"
  ],
  marketplaces: {
    denverOnlineAuctions: "https://denveronlineauctions.com/marketplace/jsg-estate-liquidation",
    ebay: "https://ebay.us/m/tsG4b9",
    liveAuctioneers: "https://jsg-liquidators.liveauctioneers.com/"
  },
  hours: "Mon-Fri 8:00-18:00 MT"
};
var get_business_info_default = defineTool5({
  name: "get_business_info",
  title: "Get JSG Liquidators business info",
  description: "Return canonical contact info, services, marketplaces, and differentiators for JSG Liquidators. Use to answer 'who is JSG', 'how do I contact them', or 'what services do they offer' questions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/index.ts
var projectRef = "mhclrysmujybkgyibxlo";
var mcp_default = defineMcp({
  name: "jsg-liquidators-mcp",
  title: "JSG Liquidators",
  version: "0.1.0",
  instructions: "Tools for JSG Liquidators \u2014 Denver's estate & business liquidation experts. Use `get_business_info` for contact/services, `list_service_areas` / `get_service_area` for Colorado city coverage, and `list_blog_posts` / `get_blog_post` for guides on estate sales, cleanouts, consignment, and junk removal.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_business_info_default, list_service_areas_default, get_service_area_default, list_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
